Add support for passing a list of tables to the validation logging functions
CancerDataAggregator/transform pull request #40
Opened 2021-02-16 18:51 UTC by pshapiro4broad

This affects `distinct`, `agree` and `validate`. Fixes #22

2021-02-16 22:02 UTC, kaushik-work requested changes

2021-02-16 22:02 UTC, kaushik-work commented on cdatransform/transform/validate.py
> +        if type(tables) is not list:
Better to use `isinstance`

2021-02-16 22:02 UTC, kaushik-work commented on cdatransform/transform/validate.py
> +        if type(tables) is not list:
Better to use `isinstance`

2021-02-16 22:16 UTC, pshapiro4broad commented on cdatransform/transform/validate.py
> +        if type(tables) is not list:
OK. Although any class that implements `__iter__` or `__getitem__` would work, not just `list`. According to the python docs:

https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable

> Checking isinstance(obj, Iterable) detects classes that are registered as Iterable or that have an __iter__() method, but it does not detect classes that iterate with the __getitem__() method. The only reliable way to determine whether an object is iterable is to call iter(obj).

2021-02-17 13:08 UTC, kaushik-work approved these changes
Thanks @pshapiro4broad

2021-02-17 15:44 UTC, merged